# Generated by Django 2.0.4 on 2018-04-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaCompra',
            fields=[
                ('idFacturaCompra', models.BigAutoField(primary_key=True, serialize=False)),
                ('idFactura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura')),
            ],
        ),
    ]
