# Generated by Django 2.0.4 on 2018-05-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturaCompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
