# Generated by Django 2.0.4 on 2018-06-06 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_auto_20180606_0105'),
        ('mediosDePago', '0002_auto_20180606_1014'),
        ('tiposDeVenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaVenta',
            fields=[
                ('idFacturaVenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idMedioDePago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediosDePago.MedioDePago')),
                ('idTipoDeVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposDeVenta.TipoDeVenta')),
            ],
            options={
                'verbose_name': 'Factura de venta',
                'verbose_name_plural': 'Facturas de venta',
            },
        ),
        migrations.CreateModel(
            name='facturaVentaContieneProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
                ('idfacturaVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturaVenta.facturaVenta')),
            ],
            options={
                'verbose_name': 'Factura de venta contiene productos',
                'verbose_name_plural': 'Facturas de venta contiene productos',
            },
        ),
    ]
