# Generated by Django 2.0.4 on 2018-06-10 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturaVenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='idMedioDePago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediosDePago.MedioDePago', verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='idTipoDeVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposDeVenta.TipoDeVenta', verbose_name='tipo de venta'),
        ),
        migrations.AlterField(
            model_name='facturaventacontieneproductos',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto', verbose_name='Producto'),
        ),
    ]
