# Generated by Django 2.0.4 on 2018-05-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturaCompraContieneProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompracontieneproductos',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto'),
        ),
    ]
