# Generated by Django 2.0.4 on 2018-05-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturaCompraContieneProductos', '0002_auto_20180521_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompracontieneproductos',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturacompracontieneproductos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
