# Generated by Django 2.0.4 on 2018-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('idMedioDePago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Medio De Pago',
                'verbose_name_plural': 'Medios De Pago',
            },
        ),
    ]
