# Generated by Django 2.0.4 on 2018-06-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediosDePago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediodepago',
            options={'verbose_name': 'Medio de pago', 'verbose_name_plural': 'Medios de pago'},
        ),
    ]
